collated: true
variants:
- name: default
  context:
    label: Button
- name: disabled
  context:
    label: Disabled button
    disabled: true
- name: more
  context:
    label: Show me more…
    href: ?page=2
    mods: [more]
